NumPy is Numerical Python used for science and Engineering field.The NumPy API is used extensively in Pandas , SciPy, Matplotlib, scikit-learn, scikit-image and other Python Packages.

In [1]:
#Installing Numpy :
!pip install numpy

In [2]:
#Importing Numpy:
import numpy as np

In [4]:
#Reading simple code:
a = np.arange(6)
a2 = a[np.newaxis, :]
a2.shape

(1, 6)

##What is the differeence between a Python list and NumPy array?

NumPy gives an enoromous range of fast and efficient ways of creating arrays and manipulating numerical data inside them. While Python list can contain different data types withn a single list, all of the elements in a NumPy array should be homogeneous. The mathematical operations that are meant to be performed on arrays would be extremely inefficient if the arrays weren't homogenous.

In [6]:
#Python List:
lst = [1,7,0,6,2,5,6]
lst

[1, 7, 0, 6, 2, 5, 6]

In [7]:
#NumPy Array:
a = np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

##Broadcasting:

Broadcasting describes how NumPy treats arrays with different shapes during arithematic operations. Subject to certain constraints, the smaller array is "broadcast" across the larger array so that they have compatible shapes.Broadcasting provides a means of vectorizing array operations so that looping occurs in C instead of Python. It does this without making needles copies of data and usually leads to efficient algorithm implementations. There are, however, cases where broadcasting is a bad idea because it leads to inefficient use of memory that slows computation.

In [8]:
a = np.array([1.0,2.0,3.0])
b = np.array([2.0,2.0,2.0])
a*b

array([2., 4., 6.])

In [9]:
a = np.array([1.0, 2.0, 3.0])
b = 2.0
a*b

array([2., 4., 6.])

##Vectorization:

Vectorization describes the use of optimized, precompiled code written in a low-level language to perform mathematical operations over a sequence of data. Vectorization allows the elimination of the for-loops in python code. It is especially important in Deep Learning as we are dealing with large numbers of datasets. So it allows the code to run quickly and helps train the algorithms faster.

In [10]:
#np.array()
arr = np.array([1,2,3,4,5,6])
arr

array([1, 2, 3, 4, 5, 6])

In [11]:
#np.zeros()
zeros_arr = np.zeros((2,3))
zeros_arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [12]:
#np.ones()
ones_arr = np.ones((3,2))
ones_arr

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [13]:
#np.reshape()
res = np.reshape(arr, (2,3))
res

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
#np.concatenate()
arr1 = np.array([1,2,3])
arr2 =  np.array([4,5,6])
con = np.concatenate((arr1, arr2))
con

array([1, 2, 3, 4, 5, 6])

In [15]:
#np.mean()
np.mean(arr)

3.5

In [16]:
#np.sum()
np.sum(arr)

21

In [17]:
#np.min()
np.min(arr)

1

In [18]:
#np.max()
np.max(arr)

6

In [19]:
#np.argmax()
np.argmax(arr) #Index of max

5

In [20]:
#np.argmin()
np.argmin(arr) #Index of min

0

In [21]:
#np.random.rand()
ran = np.random.rand(3,2)
ran

array([[0.01505186, 0.02046348],
       [0.62376762, 0.41313282],
       [0.95478957, 0.94080219]])

In [22]:
#np.random.randn()
ran_normal = np.random.randn(3,2)
ran_normal

array([[ 0.27035199,  1.03817731],
       [ 0.31730684, -2.68740378],
       [-0.14199551,  1.04048247]])

In [23]:
#np.random.randit()
random_int = np.random.randint(1, 10, size=(2, 3))
random_int

array([[3, 7, 6],
       [1, 1, 2]])

In [25]:
#np.dot()
matrix_a = np.array([[1, 2], [3, 4]])
matrix_b = np.array([[5, 6], [7, 8]])
dot_product = np.dot(matrix_a, matrix_b)
dot_product

array([[19, 22],
       [43, 50]])